### ISSUE TITLE
Spanner stops working sometimes; fixed by reloading Element

### ISSUE THREAD

**Issue by jaller94** [Half-Shot/matrix-spanner-widget#4]
If I have Element One open for a while, the spanners stop working for me and I get this timeout. It can be fixed by reloading Element Web (1.10.1 as of filing this).

![Screenshot_2022-02-07_22-50-42](https://user-images.githubusercontent.com/10872136/152879241-c50eeb6d-56d3-4b25-8b47-e864ed5a9f9f.png)

Possible related to #3 as I see that error earlier in the session.

**Comment by Half-Shot** [comment]
I think this has been okay recently.
